### ISSUE TITLE
dino/packaging: Introduce release lifecycle on the solution, to attract users

### ISSUE THREAD

**Issue by paulkatsoulakis** [nicolagi/dino#8]
Here's a proposal to help people start using it

1) decide on the versioning scheme that suits your workflow better. for example you should use alpha/beta apart from major/minor versions, since you don't have something production ready yet.

2) Create an installation script, so that users can run that to get things started. Start simple and we can enhance it later, of course a nice documentation guide for the install also would be handy (haven't seen it)

2) Get Travis CI to automatically release your software whenever you merge on the to-be-released branch (I suggest master being the clean code and tag releases)

I know this is a project on your free time, so i would gladly jump in on a few things for fun

**Comment by nicolagi** [comment]
Thanks for your thoughts!

I'm still evaluating whether this is a project worth pursuing (considering I have many others). It's working well for me, but the range of applicability is not as wide as I thought.

That being said, for versioning I'd rely only on Go standard tooling. In alpha phase, the module version is going to be something like v0.0.0-20190714201430-ac154afbcda3, which is related with the git hash. To get new releases one uses `go get -u` and to publish new releases one just does `git push`.

A getting started guide though is indeed missing. I could provide the basic information in the README.md, and perhaps to get started quickly we could provide some Dockerfile's and a tutorial?

**Comment by paulkatsoulakis** [comment]
> Thanks for your thoughts!
> 
> I'm still evaluating whether this is a project worth pursuing (considering I have many others). It's working well for me, but the range of applicability is not as wide as I thought.

I hear ya, but exactly that gap might be solved from the community very fast.
if users start trying it, you 'll definitely get more people contributing or even provide ideas and fixes.

> 
> That being said, for versioning I'd rely only on Go standard tooling. In alpha phase, the module version is going to be something like v0.0.0-20190714201430-ac154afbcda3, which is related with the git hash. To get new releases one uses `go get -u` and to publish new releases one just does `git push`.

Cool, the versioning scheme you describe from Go sounds just right.
For the release i was thinking you could start using tagging whenever you have a commit that is a good checkpoint for a new version and produce artifacts with relative documentation here: 
https://github.com/nicolagi/dino/releases

There is [hub](https://github.com/github/hub) that gives a very nice git wrapper to handle [github releases](https://hub.github.com/hub-release.1.html) and other stuff

> 
> A getting started guide though is indeed missing. I could provide the basic information in the README.md, and perhaps to get started quickly we could provide some Dockerfile's and a tutorial?

Oh yea definitely. I would even get a simple docker compose that spins up all required entities, so that users can easily see the functionality in action on a complete environment without worrying much on how it is done. With docker compose you can even orchestrate use cases once the images are spin up, to demonstrate with data what is the effect of the solution

**Comment by prologic** [comment]
> I'm still evaluating whether this is a project worth pursuing (considering I have many others). It's working well for me, but the range of applicability is not as wide as I thought.

I _accidently_ came across your project in the  search for a distributed file system, one that uses the [go-fuse](https://github.com/hanwen/go-fuse) library.

Reading your [README](https://github.com/nicolagi/dino/blob/master/README.md) it immediately struck me as being a good use-case for a problem I've always wanted to solve:

Basically, a Distributed fault-tolerant Volume for Docker Swarm services.

I _think_ I could make this work with what you've done here since you already have `dineofs` as a FUSE client and you already heavily cache various access patterns.

**Comment by nicolagi** [comment]
Archiving the project soon, hence closing all issues per [guidance].

[guidance]: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-repositories
